### ISSUE TITLE
Google Integration

### ISSUE THREAD

**Issue by manujindal77** [mtlynch/picoshare#162]
Sorry, this is more of a question that an issue.

Is there a way to integrate picoshare with Google Cloud Storage an upload the files directly in the bucket? Can this is be ported to a cloud function for easy deployment?

Thanks.

**Comment by mtlynch** [comment]
This should be possible, but I haven't tried it.

[LogPaste](https://github.com/mtlynch/logpaste/blob/master/docs/deployment/cloud-run.md) has a very similar architecture, and it supports [deploying with Cloud Run backed by Google Cloud Storage](https://github.com/mtlynch/logpaste/blob/master/docs/deployment/cloud-run.md). If you follow the same steps but swap in PicoShare instead of LogPaste, I believe it will all work already.
