### ISSUE TITLE
 files folder takes a long time to load

### ISSUE THREAD

**Issue by 3dmaksik** [mtlynch/picoshare#220]
I uploaded a file and when I go to the "files" folder, the page opens for a very long time. How to solve this problem?
![2022-04-29_22-24-09](https://user-images.githubusercontent.com/6958142/165993336-d4b457e3-3adb-42e7-a63e-c19c20d64a60.png)

**Comment by mtlynch** [comment]
Thanks for reporting this!

The issue is in this line:

https://github.com/mtlynch/picoshare/blob/de66ca0d430ebcd26766c3272b94960c368e3598/store/sqlite/sqlite.go#L124

I didn't realize that `LENGTH` has to read the data into memory, so every time it calculates the size of the file, it has to read the full data into memory.

I was able to reproduce this with a 1.13 GB file and tested a few different implementations:

| Implementation | Response time |
|-------------------|-----------------|
| `LENGTH(chunk)` ([current implementation](https://github.com/mtlynch/picoshare/tree/de66ca0d430ebcd26766c3272b94960c368e3598)) | 7.092s |
| [Store the chunk size](https://github.com/mtlynch/picoshare/compare/de66ca0d430ebcd26766c3272b94960c368e3598...store-chunk-size) | 0.744s |
| [Store the file size](https://github.com/mtlynch/picoshare/pull/221) | 0.013s |

**Comment by 3dmaksik** [comment]
Thank you for what you are doing. This is the best file storage. I'll wait for an update in the docker.
