### ISSUE TITLE
Store.db-wal file size increasing each time garbage collection is run with vacuum flag

### ISSUE THREAD

**Issue by j1303** [mtlynch/picoshare#341]
I'm running v1.2.0 from source in an Ubuntu 22.04.1 VM with the following command: "PS_SHARED_SECRET=somesecretpass PORT=3003 go run cmd/picoshare/main.go -vacuum"

It appears that with the '-vacuum' flag set, the store.db-wal file increases in size every time the garbage collection is triggered. The store.db-wal file does not grow when running without the '-vacuum' flag. It looks like the same is true with the store.db-shm file but it grows at a much slower rate.

To test this, I edited main.go to make the garbage collector run every minute. With a new empty database, the store.db-wal file increases by 28,840 bytes each time the garbage collector is run. If I upload a 100MB file, the store.db-wal file increases by ~100MB each time the garbage collector is run. If I delete the 100MB file, the store.db-wal file stops growing but the space is never reclaimed. Also, throughout testing I have not seen the size or modified date of store.db change, so it appears that it's never actually being written to.

I also saw the issue of '-vacuum' not reclaiming deleted space on a v1.2.0 docker image which is why I started looking into this in the first place. I'm trying to figure out if there's something wrong with my setup or if there's a bug here. Any help is appreciated.

**Comment by mtlynch** [comment]
Are you running with Litestream? I [saw this behavior](https://mtlynch.io/notes/picoshare-perf/#eliminating-sqlite-vacuuming) but I assumed it was Litestream holding the write-ahead log (`.db-wal` file) open, but it looks like you're not using Litestream.

I think eventually the extra space should go away as SQLite integrates the WAL file into the main DB, but I'm not sure when the integration happens or if that's client-controllable. It might be possible to issue a `pragma` to SQLite at the end of the vacuum to tell it to push the WAL into the main DB.

**Comment by mtlynch** [comment]
Thanks for digging into this, @j1303!

I'm a little reluctant to mess with the checkpointing if we can avoid it. I think a more conservative fix is to just skip the Litestream optimizations unless the user actually is using Litestream. I've prepared a fix in #342.

I've made a branch that's a little easier to test in [`litestream-pragmas-test1`](https://github.com/mtlynch/picoshare/tree/litestream-pragmas-test1). It's the same thing as #342 but it performs the vacuum every minute instead of every seven hours.

Can you test the `litestream-pragmas-test1` branch and see if it fixes your issue?

**Comment by mtlynch** [comment]
Thanks for testing, @j1303!

>I think it would be as easy as issuing PRAGMA journal_mode=WAL one time.

Good idea! We might as well use WAL mode all the time, regardless of Litestream. I've added that in 971bd13286f778ac704ca614813951a9e7305294.

I'm closing this now that #342 is merged in. That PR technically doesn't fix this because the issue still exists if you combine both vacuum and Litestream, but I think that scenario is low enough priority to close for now, and we can reopen if users run into that where they need to use both features at once.
