### ISSUE TITLE
Can't see the longpath of files in the listinfo

### ISSUE THREAD

**Issue by Quantatirsk** [mtlynch/picoshare#356]
Only when first created, one can see the fulllink of the file,  but only this moment.
In some special ocassions, I want to use the fulllink which ends with '.mp4', for example, to enable online streaming, when it is not like *.mp4, the webpage cannot load.
Could you please consider adding the fulllink info in the filelist, to enable reusing the fulllink, thank you!

**Comment by mtlynch** [comment]
I agree this should be fixed, but one workaround in the meantime is that you can manually add the filename and the link will still work.

So if the short link is `picoshare.example.com/!abc123`, then `picoshare.example.com/!abc123/foo.bar` will work because the server actually ignores everything after the file ID (the `abc123` part).

**Comment by mtlynch** [comment]
Fixed in #473, which shows the full link on the info page.
