### ISSUE TITLE
Add vacuum option to docker

### ISSUE THREAD

**Issue by fatflyingpigs** [mtlynch/picoshare#360]
Currently the default docker at https://registry.hub.docker.com/r/mtlynch/picoshare does not have the option to vacuum. Once the container is running, attempting to use the vacuum command, `./picoshare -vacuum` results in:

```
2022/12/26 19:49:10 initializing random seed
2022/12/26 19:49:10 main.go:22: Starting picoshare server
2022/12/26 19:49:10 sqlite.go:41: reading DB from data/store.db
2022/12/26 19:49:10 migrations.go:33: Migration counter: 5/5
2022/12/26 19:49:10 main.go:51: Listening on 18693
2022/12/26 19:49:10 main.go:53: listen tcp :18693: bind: address already in use
```

While the above makes sense; maybe there should be another method to clean up the db? My db has gotten as bloated as my username. Thx

**Comment by mtlynch** [comment]
Thanks for reporting this!

>Once the container is running, attempting to use the vacuum command, ./picoshare -vacuum results in:

Oh, I think there's a misunderstanding about how the `-vacuum` flag works. It looks like you're trying to run a second `./picoshare` instance with the `-vacuum` flag to clear space from the first one, but that won't work because every `./picoshare` instance expects to have exclusive access to its listen port (in your case `18693`).

You can vacuum if you run your original picoshare instance with the `-vacuum` flag. It will automatically vacuum [every seven hours](https://github.com/mtlynch/picoshare/blob/3c10b89208912930d820cdfbd983ad99e8f9224b/cmd/picoshare/main.go#L38). Unfortunately, you can't force a vacuum operation immediately, but if you leave it running with the `-vacuum` flag, it should do the right thing on schedule.

>My db has gotten as bloated as my username. Thx

😂
