### ISSUE TITLE
Killing internet

### ISSUE THREAD

**Issue by chaosclarity84** [mtlynch/picoshare#399]
I have a strange issue with Picoshare - I primarily use this to share video files (.mp4 in my case), and whenever someone is viewing one of the video files, it will randomly kill my wireless/network. I can't 100% reproduce the issue, but if I watch enough video files from shared links in Picoshare, it will eventually kill it - I have power reset the wireless access point to get it back up again. I've hosted files on Nextcloud before and never saw this issue.

Any idea what may be going on here?

**Comment by mtlynch** [comment]
What kind of wireless AP is it? I don't think this is anything specific to PicoShare because it shouldn't be possible for an app to knock out a wireless AP unless it's specifically targeting a vulnerability in the AP.

My guess is that your recipient has a high-bandwidth connection, and it's overwhelming the AP. You could test this theory by setting up iperf on a server outside of your local network and then load testing your connection to see if the same thing happens.
