### ISSUE TITLE
Downloading media instead of playback window

### ISSUE THREAD

**Issue by tiritibambix** [mtlynch/picoshare#495]
Hello !

I have this family video I want to send to several people.

When they click on the link, it launches the playback, but I want the video to be directly downloaded and not played. Most of them won't understand "right click and save as".

Is there a way to so this ? Ideally on a per media basis ?

**Comment by mtlynch** [comment]
Thanks for reaching out!

It's not supported in the app, but you could kind of hack the behavior by modifying the database.

For example, I've got a file in my PicoShare server called `IMG_3187.JPG`, so I look for its ID in the database (same as the download ID in the app):

```bash
sqlite3 data/store.db "SELECT id, filename, content_type FROM entries"
SACXgGmYbT|IMG_3187.JPG|image/jpeg
```

And then I can change its `content_type` to `application/octet-stream`, which causes most browsers to prompt for download instead of rendering it:

```bash
sqlite3 data/store.db "UPDATE entries SET content_type='application/octet-stream' WHERE id='SACXgGmYbT'"
```

Another workaround is putting the video in a zip file and telling people do download the file and unzip it. That will work without any changes to the database.

**Comment by tiritibambix** [comment]
Thank you for your answer.

My very limited knowledge of the subject prevents me from understanding these instructions in the docker container.
