### ISSUE TITLE
no space left on device, except there is

### ISSUE THREAD

**Issue by marshalleq** [mtlynch/picoshare#553]
A bit of digging shows me this error
2024/02/12 04:54:17 upload.go:61: invalid upload: write /tmp/multipart-3020920070: no space left on device

So it appears data is written to /tmp first which is never going to work for large files.  Im using docker on unraid, is this something you can fix in the code or do I need to map this manually in the container?

Thanks.

**Comment by mtlynch** [comment]
Thanks for reporting this!

It's not something that really makes sense at the application level because PicoShare assumes that the OS's default temp directory has enough space to store uploads.

The workarounds I can think of are:

- Set the `TMPDIR` environment variable in your PicoShare docker container to a path that has enough space to store uploads temporarily.
- Map the `/tmp` directory in the Docker container to a path that has enough space to store uploads.

**Comment by marshalleq** [comment]
I would suggest that /tmp is renamed to cache and that is definable by the user.  Assuming tmp is big enough is really a bit silly for a product designed to share large files, and lots of them.  Anyway, I have mapped temp elsewhere to get around it for now, and discovered two more problems sharing large files.

**Comment by mtlynch** [comment]
PicoShare isn't choosing the path for the temp directory. It's inheriting the decision from Go's standard library:

https://github.com/golang/go/blob/4619121d8491ad44884529e6294b576e4ed6296a/src/mime/multipart/formdata.go#L177

https://pkg.go.dev/os#CreateTemp
