### ISSUE TITLE
Show disk utilization on server

### ISSUE THREAD

**Issue by mtlynch** [mtlynch/picoshare#86]
It would be helpful to expose disk space (used, free) in the web UI so that the user understands how much space they have left.

**Comment by viktorpenelski** [comment]
I think this is useful and can probably open a (draft) PR at some point this week.

Got a few questions though, both from a design and an implementation standpoint.

**1. Design**

**1.1 How should the info be presented?**
I'm thinking something similar to the way google drive is presenting it, but there may be nicer ways as well.

![image](https://user-images.githubusercontent.com/9766351/165145375-099499fa-2e1c-473b-9b87-5029ebb41aba.png)

Also with an icon or without an icon?
Maybe also a "pie" or "bar" chart would be nice, but I'd leave that for a v2, because of my limited UI skills 😅

**1.2 Where should the info be located?**
I'm really bad at figma, but gave it a shot to show a few ideas I have in mind, open to other suggestions as well!
https://www.figma.com/file/A60pJD5Jf39vJDRoCAHAA1/PicoShare-disk-utilization

**2. Implementation**
I looked around for ways to query this kind of info from the OS in Golang and found the [syscall](https://pkg.go.dev/syscall) package. That one is deprecated though. It seems to have been replaced by `golang.org/x/sys/unix`, from where I plan to use `Statfs`. That would be only usable on UNIX-based OSs. 
Do you think that's OK for the initial implementation?

Alternatively, we could use some 3rd party library for this, but at least in my quick github search, I didn't find anything actively maintained (e.g. https://github.com/ricochet2200/go-disk-usage uses the deprecated "syscall" import)

My initial hunch is to go without 3rd party library, support only linux for starters (as I expect docker would be the most common way to use picoshare?), and handle the lack of this info gracefully (e.g. just don't display the info on the frontend when it is missing).
Having the initial implementation/plumbing in place, it should be easy subsequently to either implement more platforms or to replace the low-level implementation with a higher-level cross-platform library.

**Comment by mtlynch** [comment]
>I think this is useful and can probably open a (draft) PR at some point this week.

Awesome, that would be great!

>How should the info be presented?

Yeah, I like the Google drive style with a simple bar. But even just having numbers and no graphics would be good for a v1.

>Where should the info be located?

I don't think it's so important that we need to show it all the time. I think we could bury it in a menu a little. How about changing "Account" to "System" and putting it there?

![image](https://user-images.githubusercontent.com/7783288/165402934-7d9edeaf-ab6d-457a-9fc8-e92a7e9c3813.png)

>I plan to use Statfs. That would be only usable on UNIX-based OSs. Do you think that's OK for the initial implementation?

Yep `Statfs` works for me. I don't mind excluding Windows support on this. I doubt anyone is running PicoShare on Windows directly without Docker.

**Comment by igorferreir4** [comment]
>
> **1.2 Where should the info be located?** I gave figma a try to show some ideas that come to mind, open to other suggestions as well! https://www.figma.com/file/A60pJD5Jf39vJDRoCAHAA1/PicoShare-disk-utilization
> 

I vote for option 4
